version: "3"
services:
   Squid:
     image: sameersbn/squid:3.5.27-2
     ports:
      - "3128:3128"
     volumes:
       - ./docker/squid/cache:/var/spool/squid
       - ./squid.conf:/etc/squid/squid.conf  
     restart: always
